#!/usr/bin/env python3
"""用 SQLite 冒烟测试 schema_pg.sql + refresh_pg.sql 的「两件套交付合同」（v0.4 业务口径）。

数据全部是合成的（example.gov.cn / example.com），只验证约束和选择逻辑，不代表真实项目。
运行：python3 docs/national_eia_db/smoke_test_sqlite.py
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

GUARD_WHEN = """
NEW.delivery_status IN ('COMPLETE','LINK_REVIEW') AND (
     NOT EXISTS (SELECT 1 FROM file_blob WHERE sha256 = NEW.report_sha256   AND verified)
  OR NOT EXISTS (SELECT 1 FROM file_blob WHERE sha256 = NEW.approval_sha256 AND verified)
  OR NOT EXISTS (SELECT 1 FROM attachment a JOIN notice n ON n.notice_id = a.notice_id
                   JOIN entry e ON e.entry_id = n.entry_id JOIN site s ON s.site_id = e.site_id
                   JOIN dict_source_class sc ON sc.code = s.source_class
                 WHERE a.att_id = NEW.report_att_id AND a.blob_sha256 = NEW.report_sha256
                   AND a.on_official_host AND sc.deliverable)
  OR NOT EXISTS (SELECT 1 FROM attachment a JOIN notice n ON n.notice_id = a.notice_id
                   JOIN entry e ON e.entry_id = n.entry_id JOIN site s ON s.site_id = e.site_id
                   JOIN dict_source_class sc ON sc.code = s.source_class
                 WHERE a.att_id = NEW.approval_att_id AND a.blob_sha256 = NEW.approval_sha256
                   AND a.on_official_host AND sc.deliverable)
  OR EXISTS (SELECT 1 FROM eia_case WHERE case_id = NEW.case_id AND scope <> 'IN_SCOPE'))
"""
SQLITE_GUARD = f"""
CREATE TRIGGER delivery_guard_ins BEFORE INSERT ON case_delivery WHEN {GUARD_WHEN}
BEGIN SELECT RAISE(ABORT, '交付行必须是两份已校验、来自官方网站、范围内的文件'); END;
CREATE TRIGGER delivery_guard_upd BEFORE UPDATE ON case_delivery WHEN {GUARD_WHEN}
BEGIN SELECT RAISE(ABORT, '交付行必须是两份已校验、来自官方网站、范围内的文件'); END;
"""


def to_sqlite(sql: str) -> str:
    sql = re.sub(r"-- @pg-only-begin.*?-- @pg-only-end", "", sql, flags=re.S)
    sql = sql.replace("bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY")
    return sql.replace("text[]", "text")


def sha(ch: str) -> str:
    return ch * 64


SITE_HOST = {1: "sthjj.example.gov.cn", 2: "portal.example.gov.cn", 3: "xzsp.example.gov.cn", 4: "agg.example.com"}
# entry_id → (阶段, site_id)
ENTRIES = {
    1: ("ACCEPT", 1), 2: ("PRE_APPROVAL", 1), 3: ("APPROVAL", 1),   # 环保局自有网站
    4: ("ACCEPT", 3),                                                  # 行政审批局网站
    5: ("APPROVAL", 2),                                                # 区政府门户上的环保局栏目
    6: ("ACCEPT", 4),                                                  # 第三方聚合平台
    7: ("ACCEPT_PRE_APPROVAL", 1),                                     # 受理和拟审批合并公示
}


def main() -> int:
    db = sqlite3.connect(":memory:", isolation_level=None)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA foreign_keys = ON")
    db.executescript(to_sqlite((HERE / "schema_pg.sql").read_text(encoding="utf-8")))
    db.executescript(SQLITE_GUARD)

    db.executescript("""
    INSERT INTO region VALUES ('320000','江苏省','province',NULL), ('320500','苏州市','city','320000');
    INSERT INTO authority (authority_id, authority_code, name, region_code, authority_type)
      VALUES (1, '320500-SZSTHJJ', '苏州市生态环境局', '320500', 'CITY_EEB');
    INSERT INTO site (site_id, root_url, name, owner_authority_id, source_class, official_evidence) VALUES
      (1, 'https://sthjj.example.gov.cn',  '合成·环保局网站',         1, 'EEB_OWN_SITE',        '合成：政府网站标识码'),
      (2, 'https://portal.example.gov.cn', '合成·区政府门户环保局栏目', 1, 'EEB_PORTAL_COLUMN',   '合成：区政府门户栏目'),
      (3, 'https://xzsp.example.gov.cn',   '合成·行政审批局网站',       1, 'OTHER_APPROVER_SITE', '合成：ICP 备案主体为行政审批局'),
      (4, 'https://agg.example.com',       '合成·第三方聚合平台',       NULL, 'THIRD_PARTY',      NULL);
    INSERT INTO entry (entry_id, entry_code, site_id, name, list_url, adapter, stage_hint, status) VALUES
      (1, '320500-SZSTHJJ-ACCEPT-01',       1, '受理公示',          'https://sthjj.example.gov.cn/sl/',   'trs', 'ACCEPT',              'active'),
      (2, '320500-SZSTHJJ-PRE_APPROVAL-01', 1, '拟审批公示',        'https://sthjj.example.gov.cn/nsp/',  'trs', 'PRE_APPROVAL',        'active'),
      (3, '320500-SZSTHJJ-APPROVAL-01',     1, '批准项目公告',      'https://sthjj.example.gov.cn/pz/',   'trs', 'APPROVAL',            'active'),
      (4, '320500-XZSP-ACCEPT-01',          3, '受理公示',          'https://xzsp.example.gov.cn/sl/',    'trs', 'ACCEPT',              'active'),
      (5, '320500-PORTAL-APPROVAL-01',      2, '环保局·审批公告',    'https://portal.example.gov.cn/hb/',  'trs', 'APPROVAL',            'active'),
      (6, '320500-AGG-ACCEPT-01',           4, '聚合·受理公示',      'https://agg.example.com/sl/',        'api', 'ACCEPT',              'active'),
      (7, '320500-SZSTHJJ-MERGED-01',       1, '受理和拟审批公示',   'https://sthjj.example.gov.cn/slnsp/','trs', 'ACCEPT_PRE_APPROVAL', 'active');
    INSERT INTO crawl_run (run_id, entry_id, mode, code_version) VALUES
      (1,1,'full','test'), (2,2,'full','test'), (3,3,'full','test'), (4,4,'full','test'),
      (5,5,'full','test'), (6,6,'full','test'), (7,7,'full','test');
    """)

    def case(cid: int, decided: bool = True, approval_date: str = "2026-04-20") -> None:
        db.execute(
            "INSERT INTO eia_case (case_id, case_code, authority_id, region_code, project_name, project_name_norm,"
            " lifecycle, approval_doc_no_norm, approval_date) VALUES (?,?,1,'320500',?,?,?,?,?)",
            (cid, f"EIA-320500-2026-{cid:06d}", f"合成项目{cid}", f"合成项目{cid}",
             "DECIDED" if decided else "SEEN_ACCEPT",
             f"苏环建[2026]{cid}号" if decided else None, approval_date if decided else None))

    def notice(nid: int, entry: int, cid: int, *, score: float = 1.0, key: str = "SEED", pub: str = "2026-04-01",
               radiation: bool = False, mode: str = "STANDARD", decision: str = "UNKNOWN") -> None:
        """一条公告 + 其中一个项目行 + 关联到事项（可以没有附件，如只列名单的拟审批公示）。"""
        stage, site = ENTRIES[entry]
        db.execute(
            "INSERT INTO notice (notice_id, entry_id, first_run_id, url, title, pub_date, authority_id, stage,"
            " stage_method, relevance, fetch_status) VALUES (?,?,?,?,?,?,1,?,'entry_hint','eia','fetched')",
            (nid, entry, entry, f"https://{SITE_HOST[site]}/n/{nid}.shtml", f"合成公告{nid}", pub, stage))
        db.execute(
            "INSERT INTO notice_item (item_id, notice_id, project_name_raw, project_name_norm, norm_version,"
            " is_radiation, approval_mode, decision) VALUES (?,?,?,?,'v1',?,?,?)",
            (nid, nid, f"合成项目{cid}", f"合成项目{cid}", radiation, mode, decision))
        db.execute(
            "INSERT INTO case_item_link (item_id, case_id, match_key, score, state, decided_by)"
            " VALUES (?,?,?,?,'accepted','rule:test')", (nid, cid, key, score))

    def add(nid: int, entry: int, cid: int, role: str, blob: str | None, *, verified: bool = True,
            netdisk: bool = False, version: str = "UNKNOWN", **kw) -> None:
        notice(nid, entry, cid, **kw)
        stage, site = ENTRIES[entry]
        host = "pan.example.com" if netdisk else SITE_HOST[site]
        if blob:
            db.execute(
                "INSERT OR IGNORE INTO file_blob (sha256, size_bytes, ext, storage_uri, pages, verified)"
                " VALUES (?,1000,'pdf',?,10,?)", (blob, f"oss://test/blob/{blob[:2]}/{blob}.pdf", verified))
        db.execute(
            "INSERT INTO attachment (att_id, notice_id, item_id, kind, url, url_host, on_official_host, anchor_text, ext,"
            " doc_role, role_method, version_label, blob_sha256, fetch_status)"
            " VALUES (?,?,?,?,?,?,?,?,'pdf',?,'name_rule',?,?,?)",
            (nid, nid, nid, "netdisk" if netdisk else "file", f"https://{host}/f/{nid}.pdf", host, not netdisk,
             f"附件{nid}", role, version, blob, "ok" if blob else "netdisk_manual"))
        db.execute("INSERT INTO case_document (case_id, att_id, role, source_stage) VALUES (?,?,?,?)",
                   (cid, nid, role, stage))

    # 1 受理版 + 拟审批版 + 批复 → 取拟审批版
    case(1)
    add(101, 1, 1, "report", sha("a"), score=0.92, key="BUILDER_NAME_EXACT", pub="2026-03-01")
    add(102, 2, 1, "report", sha("b"), score=0.95, key="BUILDER_NAME_EXACT", pub="2026-04-01")
    add(103, 3, 1, "approval", sha("c"), pub="2026-04-20")
    # 2 只有受理版 + 批复，拟审批公示没抓到 → 兜底，可升级
    case(2)
    add(201, 1, 2, "report", sha("d"), score=0.98, key="PROJECT_CODE")
    add(202, 3, 2, "approval", sha("e"))
    # 3 只有批复 → 缺报告
    case(3)
    add(301, 3, 3, "approval", sha("f"))
    # 4 名称模糊匹配 0.72 → 带标记交付
    case(4)
    add(401, 1, 4, "report", sha("1"), score=0.72, key="NAME_FUZZY")
    add(402, 3, 4, "approval", sha("2"))
    # 5 只受理、未决定 → 等待审批
    case(5, decided=False)
    add(501, 1, 5, "report", sha("3"))
    # 6 拟审批版文件损坏 → 落到受理版（拟审批公示已抓到，不再标可升级）
    case(6)
    add(601, 2, 6, "report", sha("4"), verified=False, score=0.95, key="DOC_NO")
    add(602, 1, 6, "report", sha("5"), score=0.95, key="BUILDER_NAME_EXACT")
    add(603, 3, 6, "approval", sha("6"))
    # 7 辐射类 → 范围外
    case(7)
    add(701, 1, 7, "report", sha("7"), radiation=True)
    add(702, 3, 7, "approval", sha("8"))
    # 8 告知承诺制 → 范围外
    case(8)
    add(801, 1, 8, "report", sha("9"))
    add(802, 3, 8, "approval", sha("g"), mode="COMMITMENT")
    # 9 不予批准 → 范围外
    case(9)
    add(901, 1, 9, "report", sha("h"))
    add(902, 3, 9, "approval", sha("i"), decision="REJECT")
    # 10 批复在 2021-01-01 之前 → 范围外
    case(10, approval_date="2020-11-20")
    add(1001, 1, 10, "report", sha("j"), pub="2020-10-01")
    add(1002, 3, 10, "approval", sha("k"), pub="2020-11-20")
    # 11 报告在行政审批局网站 → 可交付
    case(11)
    add(1101, 4, 11, "report", sha("l"))
    add(1102, 3, 11, "approval", sha("m"))
    # 12 报告只有网盘链接 → 缺报告，原因：非官方来源
    case(12)
    add(1201, 1, 12, "report", None, netdisk=True)
    add(1202, 3, 12, "approval", sha("n"))
    # 13 批复在区政府门户的环保局栏目 → 可交付
    case(13)
    add(1301, 1, 13, "report", sha("o"))
    add(1302, 5, 13, "approval", sha("p"))
    # 14 报告只在第三方聚合平台 → 缺报告，原因：非官方来源
    case(14)
    add(1401, 6, 14, "report", sha("q"))
    add(1402, 3, 14, "approval", sha("r"))
    # 15 受理和拟审批合并公示里的报批稿 + 单独受理公示的公示文本（更新）→ 取合并公示版，不算兜底
    case(15)
    add(1501, 7, 15, "report", sha("s"), version="SUBMITTED_FOR_APPROVAL", pub="2026-03-10")
    add(1502, 1, 15, "report", sha("t"), version="PUBLIC_DRAFT", pub="2026-03-20")
    add(1503, 3, 15, "approval", sha("u"))
    # 16 受理阶段两份：较新的公示文本、较早的报批稿 → 取报批稿
    case(16)
    add(1601, 1, 16, "report", sha("v"), version="PUBLIC_DRAFT", pub="2026-03-20")
    add(1602, 1, 16, "report", sha("w"), version="SUBMITTED_FOR_APPROVAL", pub="2026-03-01")
    add(1603, 3, 16, "approval", sha("x"))
    # 17 昆山唯斯达的情况：拟审批公示抓到了但没附件，批复公告只附批复 → 兜底，但审批阶段已查过
    case(17)
    add(1701, 1, 17, "report", sha("y"), pub="2026-03-01")
    notice(1702, 2, 17, pub="2026-04-07")
    add(1703, 3, 17, "approval", sha("z"), pub="2026-04-14")

    refresh = (HERE / "refresh_pg.sql").read_text(encoding="utf-8")
    db.executescript(refresh)
    db.executescript(refresh)  # 幂等：跑两遍结果不变

    failures = 0

    def check(label: str, got, want) -> None:
        nonlocal failures
        ok = got == want
        failures += not ok
        print(f"  {'PASS' if ok else 'FAIL'} {label}: {got}" + ("" if ok else f"  期望 {want}"))

    expected = {
        1: ("COMPLETE", "PRE_APPROVAL", 0, 0.95),
        2: ("COMPLETE", "ACCEPT", 1, 0.98),
        3: ("MISSING_REPORT", None, None, 1),
        4: ("LINK_REVIEW", "ACCEPT", 1, 0.72),
        5: ("PENDING_DECISION", "ACCEPT", 1, 1),
        6: ("COMPLETE", "ACCEPT", 1, 0.95),
        7: ("OUT_OF_SCOPE", None, None, None),
        8: ("OUT_OF_SCOPE", None, None, None),
        9: ("OUT_OF_SCOPE", None, None, None),
        10: ("OUT_OF_SCOPE", None, None, None),
        11: ("COMPLETE", "ACCEPT", 1, 1),
        12: ("MISSING_REPORT", None, None, 1),
        13: ("COMPLETE", "ACCEPT", 1, 1),
        14: ("MISSING_REPORT", None, None, 1),
        15: ("COMPLETE", "ACCEPT_PRE_APPROVAL", 0, 1),
        16: ("COMPLETE", "ACCEPT", 1, 1),
        17: ("COMPLETE", "ACCEPT", 1, 1),
    }
    print("交付结果")
    for r in db.execute("SELECT d.case_id, d.delivery_status, d.report_stage, d.report_is_fallback, d.pair_confidence,"
                        " d.report_source_class, d.approval_source_class, c.scope"
                        " FROM case_delivery d JOIN eia_case c USING (case_id) ORDER BY d.case_id"):
        check(f"case {r['case_id']:>2} scope={r['scope']:<16} 报告来源={r['report_source_class']} "
              f"审批意见来源={r['approval_source_class']}",
              (r["delivery_status"], r["report_stage"], r["report_is_fallback"], r["pair_confidence"]),
              expected[r["case_id"]])

    picked = {r["case_id"]: (r["report_att_id"], r["report_version_label"])
              for r in db.execute("SELECT case_id, report_att_id, report_version_label FROM case_delivery WHERE case_id IN (15, 16)")}
    check("审批阶段合并公示与同阶段版本排序（选中的报告附件）", picked,
          {15: (1501, "SUBMITTED_FOR_APPROVAL"), 16: (1602, "SUBMITTED_FOR_APPROVAL")})

    upgrade = {r["case_id"]: (r["seen_pre_approval_notice"], r["report_upgrade_possible"])
               for r in db.execute("SELECT case_id, seen_pre_approval_notice, report_upgrade_possible FROM case_delivery"
                                   " WHERE case_id IN (1, 2, 6, 15, 17)")}
    check("兜底能否升级（已抓到拟审批公示, 可能有更好版本）", upgrade,
          {1: (1, 0), 2: (0, 1), 6: (1, 0), 15: (1, 0), 17: (1, 0)})

    scopes = {r["case_id"]: r["scope"] for r in db.execute("SELECT case_id, scope FROM eia_case WHERE case_id BETWEEN 7 AND 10")}
    check("范围外原因", scopes, {7: "OUT_RADIATION", 8: "OUT_COMMITMENT", 9: "OUT_REJECTED", 10: "OUT_BEFORE_START"})

    gaps = [tuple(r) for r in db.execute("SELECT case_id, role, reason_code FROM case_gap ORDER BY case_id, role")]
    check("缺口登记", gaps, [(3, "report", "NOT_YET_CRAWLED"), (5, "approval", "PENDING_DECISION"),
                          (12, "report", "NOT_OFFICIAL_SOURCE"), (14, "report", "NOT_OFFICIAL_SOURCE")])

    check("复核任务跑两遍只开 1 个", db.execute("SELECT COUNT(*) FROM review_task").fetchone()[0], 1)

    export = [r[0] for r in db.execute("SELECT case_code FROM v_delivery_export ORDER BY case_code")]
    check("对外交付视图", [c[-2:] for c in export], ["01", "02", "04", "06", "11", "13", "15", "16", "17"])

    # 升级：事项 2 先交付了受理版，之后抓到批复公告里附的报告 → 重跑自动替换
    add(203, 3, 2, "report", sha("0"), pub="2026-04-20", version="SUBMITTED_FOR_APPROVAL")
    db.executescript(refresh)
    r = db.execute("SELECT report_att_id, report_stage, report_is_fallback, report_upgrade_possible FROM case_delivery"
                   " WHERE case_id = 2").fetchone()
    check("后抓到批复公告附的报告，重跑自动升级", tuple(r), (203, "APPROVAL", 0, 0))

    print("\n约束必须拒绝的写入")
    copy_cols = ("report_att_id, report_sha256, report_stage, report_is_fallback, report_file_url, report_notice_url,"
                 " report_entry_code, report_source_class, approval_att_id, approval_sha256, approval_file_url,"
                 " approval_notice_url, approval_entry_code, approval_source_class, pair_confidence")
    must_fail = [
        ("交付行去掉报告来源链", "UPDATE case_delivery SET report_notice_url = NULL WHERE case_id = 1"),
        ("交付行换成未校验文件", f"UPDATE case_delivery SET report_sha256 = '{sha('4')}', report_att_id = 601 WHERE case_id = 6"),
        ("报告和审批意见是同一个文件", "UPDATE case_delivery SET approval_sha256 = report_sha256 WHERE case_id = 1"),
        ("关联分 0.72 却标 COMPLETE", "UPDATE case_delivery SET delivery_status = 'COMPLETE' WHERE case_id = 4"),
        ("带标记交付但关联分只有 0.5", "UPDATE case_delivery SET pair_confidence = 0.5 WHERE case_id = 4"),
        ("缺报告却标 COMPLETE", "UPDATE case_delivery SET delivery_status = 'COMPLETE' WHERE case_id = 3"),
        ("报告换成第三方平台的文件",
         f"UPDATE case_delivery SET report_att_id = 1401, report_sha256 = '{sha('q')}' WHERE case_id = 13"),
        ("报告指向网盘链接", "UPDATE case_delivery SET report_att_id = 1201 WHERE case_id = 13"),
        ("范围外事项标为交付",
         f"UPDATE case_delivery SET (delivery_status, {copy_cols}) = "
         f"(SELECT 'COMPLETE', {copy_cols} FROM case_delivery WHERE case_id = 1) WHERE case_id = 7"),
        ("接受一条 0.5 分的关联", "UPDATE case_item_link SET score = 0.5 WHERE item_id = 401"),
        ("网盘链接标为官方域名", "UPDATE attachment SET on_official_host = true WHERE att_id = 1201"),
        ("官方等级却没写判定依据",
         "INSERT INTO site (root_url, name, source_class) VALUES ('https://new.example.gov.cn', 'x', 'OTHER_APPROVER_SITE')"),
        ("一个项目行归属两个事项",
         "INSERT INTO case_item_link (item_id, case_id, match_key, score, state, decided_by)"
         " VALUES (101, 2, 'MANUAL', 1, 'accepted', 'reviewer:test')"),
        ("同一事项选中两份报告", "UPDATE case_document SET selected = true WHERE case_id = 1 AND role = 'report'"),
        ("同一机关重复批复文号",
         "INSERT INTO eia_case (case_id, case_code, authority_id, region_code, project_name, project_name_norm,"
         " approval_doc_no_norm) VALUES (99, 'EIA-320500-2026-000099', 1, '320500', 'x', 'x', '苏环建[2026]1号')"),
    ]
    for label, sql in must_fail:
        try:
            db.execute(sql)
        except sqlite3.DatabaseError as e:
            print(f"  PASS {label} → 被拒绝：{e}")
        else:
            failures += 1
            print(f"  FAIL {label} → 竟然写进去了")

    print(f"\n{'全部通过' if failures == 0 else f'{failures} 项失败'}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
